change job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,7 +11,7 @@ on:
       - checks_requested
 
 jobs:
-  lint:
+  setup:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -20,37 +20,83 @@ jobs:
       - name: Setup
         uses: ./.github/actions/setup
 
-#      - name: Set up Node.js
-#        uses: actions/setup-node@v3
-#        with:
-#          node-version-file: .nvmrc
-#
-#      - name: Install Yarn
-#        run: |
-#          curl -o- -L https://yarnpkg.com/install.sh | bash
-##          export PATH="$HOME/.yarn/bin:$PATH"
-#
-#      - name: Check for yarn.lock
-#        run: |
-#          if [ ! -f yarn.lock ]; then
-#            echo "yarn.lock file is missing. Please run 'yarn install' to generate one."
-#            exit 1
-#          fi
-#
-#      - name: Install dependencies
-#        run: yarn install
+  lint:
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-      - name: Lint files
+      - name: Run Lint
         run: yarn lint
 
-      - name: Typecheck files
+  typecheck:
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Run Type Check
         run: yarn typecheck
 
-      - name: Run unit tests
+  test:
+    runs-on: ubuntu-latest
+    needs: [lint, typecheck]
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Run Tests
         run: yarn test --maxWorkers=2 --coverage
 
-      - name: Upload coverage to Codecov
+  upload-coverage:
+    runs-on: ubuntu-latest
+    needs: test
+    steps:
+      - name: Upload Coverage to Codecov
         run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.COVERAGE_KEY }} -f coverage/lcov.info
+
+#  lint1:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v3
+#
+#      - name: Setup
+#        uses: ./.github/actions/setup
+#
+##      - name: Set up Node.js
+##        uses: actions/setup-node@v3
+##        with:
+##          node-version-file: .nvmrc
+##
+##      - name: Install Yarn
+##        run: |
+##          curl -o- -L https://yarnpkg.com/install.sh | bash
+###          export PATH="$HOME/.yarn/bin:$PATH"
+##
+##      - name: Check for yarn.lock
+##        run: |
+##          if [ ! -f yarn.lock ]; then
+##            echo "yarn.lock file is missing. Please run 'yarn install' to generate one."
+##            exit 1
+##          fi
+##
+##      - name: Install dependencies
+##        run: yarn install
+#
+#      - name: Lint files
+#        run: yarn lint
+#
+#      - name: Typecheck files
+#        run: yarn typecheck
+#
+#      - name: Run unit tests
+#        run: yarn test --maxWorkers=2 --coverage
+#
+#      - name: Upload coverage to Codecov
+#        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.COVERAGE_KEY }} -f coverage/lcov.info
 
 #  build-library:
 #    runs-on: ubuntu-latest
